name: Build and deploy Node.js backend to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: |
          cd backend
          npm install
          # Optionally run tests or build steps if needed

      - name: Zip the backend
        run: |
          cd backend
          zip -r ../backend.zip .   # everything in backend folder

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifact
          path: backend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-artifact

      - name: Unzip artifact
        run: unzip backend.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'video-sharing-backend'  # your Web App name
          package: './backend'               # path to the unzipped folder
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          # slot-name: 'production' # only if you created a separate slot
