name: Build and Deploy Node.js Backend to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: |
          cd backend
          npm install
          # (Optionally, run build/test if needed)
          # npm run build --if-present
          # npm test --if-present

      - name: Zip the backend folder contents
        run: |
          cd backend
          zip -r ../backend.zip .   # Zips the contents of 'backend'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifact
          path: backend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-artifact

      - name: Unzip artifact
        run: unzip backend.zip -d deploy

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'video-sharing-backend'  # Your Azure App Service name
          package: 'deploy'                   # Updated path to 'deploy'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          # If you have a slot, add:
          # slot-name: 'your-slot-name'
